#!/usr/bin/env bash

script_root=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

view_options=

if [ ${ENV_NO_COLOR:-0} -eq 1 ]; then
    view_options="${view_options} --no-color"
fi

if [ ${ENV_WIDTH:-0} -ne 0 ]; then
    view_options="${view_options} --width ${ENV_WIDTH}"
else
    w=$(tput cols)
    ENV_WIDTH=$((w/2-7))        # to avoid too long text line occupy multiple view line.
    view_options="${view_options} --width ${ENV_WIDTH}"
fi

if [ ${ENV_HTML:-0} -eq 1 ]; then
    view_options="${view_options} --html"
fi

if [ ${ENV_BY_CHAR:-0} -eq 1 ]; then
    view_options="${view_options} --bychar"
fi

if [ ${ENV_HTML:-0} -eq 1 ]; then
    git --no-pager diff $* | "${script_root}"/parse.py | "${script_root}"/view.py ${view_options}
else
    if [ ${ENV_OUTPUT_FILE:-''} != '' ]; then
        git --no-pager diff $* | "${script_root}"/parse.py | "${script_root}"/view.py -c ${view_options} | tee ${ENV_OUTPUT_FILE} | less -R
    else
        git --no-pager diff $* | "${script_root}"/parse.py | "${script_root}"/view.py -c ${view_options} | less -R
    fi
fi
